// Generated by CoffeeScript 1.3.3

_.extend(Template.accomplish, {
  events: {
    'click .create': function(e) {
      var data, story;
      if (!e.isPropagationStopped()) {
        e.stopPropagation();
        story = $("#editor").val();
        this.tags || (this.tags = []);
        data = {
          entity: this._id,
          entityType: 'achievement',
          story: story,
          tags: this.tags
        };
        Meteor.call('accomplish', data, function(error, result) {
          return window.Router.navigate("/accomplishments/" + result, true);
        });
        return Session.set('modal', this._id);
      }
    },
    'click .uncreate': function(e) {
      return Accomplishments.remove(this._id);
    },
    'click a.editor': function(e) {
      console.log('test');
      $('.editor').hide();
      return $('.preview').show();
    },
    'click a.preview': function(e) {
      $('.editor').show();
      return $('.preview').hide();
    }
  },
  accomplishment: function() {
    return Accomplishments.findOne({
      user: Meteor.user()._id,
      entity: this._id
    });
  },
  story: function() {
    var acpl;
    acpl = Accomplishments.findOne({
      user: Meteor.user()._id,
      entity: this._id
    });
    if (acpl) {
      if (acpl.story) {
        return acpl.story;
      }
    }
    return '';
  },
  rendered: function() {
    return $('#editor').markdownEditor({
      toolbarLoc: $("#toolbar"),
      toolbar: "default",
      preview: $("#preview")
    });
  }
});
