// Generated by CoffeeScript 1.3.3

_.extend(Template.titles, {
  titles: function() {
    var titles;
    titles = Titles.find({
      entity: this._id,
      user: Meteor.user()._id
    }, {
      sort: {
        score: -1
      }
    });
    if (titles.count() === 0) {
      return false;
    }
    return titles;
  },
  user: function() {
    return Meteor.users.findOne(this.user);
  }
});
