// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.accounts.facebook.config('306419872769911', 'http://localhost:3000', {
    scope: ["user_about_me", "user_location", "user_photos", "user_videos"]
  });

}).call(this);
