// Generated by CoffeeScript 1.3.3

_.extend(Template.achievers, {
  accomplishments: function() {
    var accomplishments, sel, sort, test, user, username;
    username = Session.get('username');
    if (username) {
      user = Meteor.users.findOne({
        username: username
      });
      if (user) {
        sel = Template.accomplishments.select();
        _.extend(sel, {
          user: user._id,
          entity: this._id
        });
        test = Accomplishments.find(sel);
        sort = Template.filter.sort();
        accomplishments = Accomplishments.find(sel, {
          sort: sort,
          limit: 3 * (Session.get('skip') + 1)
        });
        if (test.count() === 0) {
          return false;
        } else {
          return accomplishments;
        }
      }
    }
  }
});
