// Generated by CoffeeScript 1.3.3

_.extend(Template.accomplish, {
  events: {
    'click .create': function(e) {
      var data;
      if (!e.isPropagationStopped()) {
        e.stopPropagation();
        data = Scratchpad.findOne({
          type: 'accomplishment',
          entity: this._id
        });
        return Meteor.call('accomplish', data, function(error, result) {
          return window.Router.navigate("/accomplishments/" + result, true);
        });
      }
    },
    'change .lazy': function(e) {
      var $t, data, field;
      data = {};
      $t = $(e.currentTarget);
      field = $t.attr('name');
      data[field] = $t.val();
      return Scratchpad.update(this._id, {
        $set: data
      });
    },
    'click .uncreate': function(e) {
      return Accomplishments.remove(this._id);
    },
    'click a.editor': function(e) {
      $('.editor').hide();
      return $('.preview').show();
    },
    'click a.preview': function(e) {
      $('.editor').show();
      return $('.preview').hide();
    },
    'change #upload': function(evt) {}
  },
  newAccomplishment: function() {
    return Scratchpad.findOne({
      type: 'accomplishment',
      entity: Session.get('single')
    });
  },
  accomplishment: function() {
    return Accomplishments.findOne({
      user: Meteor.user()._id,
      entity: this._id
    });
  },
  rendered: function() {
    return $('#editor').markdownEditor({
      toolbarLoc: $("#toolbar"),
      toolbar: "default",
      preview: $("#preview")
    });
  }
});
