// Generated by CoffeeScript 1.3.3

_.extend(Template.header, {
  events: function() {
    return {
      'click .category .nav-item': function(e) {
        var $t, category;
        $t = $(e.target).closest('.category');
        category = $t.data('category');
        return Session.set('category', category);
      }
    };
  },
  rendered: function() {
    $('.popover').remove();
    return $('.spell').popover({
      placement: 'bottom',
      trigger: 'hover'
    });
  },
  pic: function() {
    var fbid, user;
    user = Meteor.user();
    if (user) {
      if (user.services) {
        fbid = _.escape(user.services.facebook.id);
        return "<img src='https://graph.facebook.com/" + fbid + "/picture'/>";
      }
    }
  },
  items: function() {
    var user;
    if (Meteor.user()) {
      user = Meteor.user();
      return Skills.find({
        level: {
          $lte: user.level
        }
      });
    }
  },
  cooldownText: function() {
    if (this.cooldown != null) {
      if (this.cooldown === 1) {
        return '1 second cooldown';
      } else {
        return "" + this.cooldown + " seconds cooldown";
      }
    } else {
      return '';
    }
  },
  isPassive: function() {
    if (this.passive) {
      return 'passive';
    } else {
      return '';
    }
  },
  numNotifications: function() {
    var user;
    if (Meteor.user()) {
      user = Meteor.user()._id;
      return Notifications.find({
        user: {
          $ne: user
        },
        receivers: user,
        seen: {
          $ne: user
        }
      }).count();
    }
  }
});
