// Generated by CoffeeScript 1.3.3

_.extend(Template.loadMore, {
  events: {
    'click .more': function(e) {
      var skip;
      skip = Session.get('skip');
      skip++;
      return Session.set('skip', skip);
    }
  }
});
