// Generated by CoffeeScript 1.3.3

_.extend(Template.miniTitles, {
  titles: function() {
    var titles;
    return titles = Titles.find({
      entity: this._id,
      user: Meteor.user()._id
    }, {
      sort: {
        score: -1
      },
      limit: 5
    });
  }
});
