// Generated by CoffeeScript 1.3.3

_.extend(Template.notification, {
  user: function() {
    return Meteor.users.findOne(this.user);
  },
  isTitle: function(type) {
    return type === 'title';
  },
  title: function() {
    var t;
    t = Titles.findOne(this.target);
    if (t) {
      return t.title;
    }
  },
  vote: function(type) {
    return type === 'vote';
  },
  accomplishment: function(type) {
    return type === 'accomplishment';
  },
  achievement: function(type) {
    return type === 'achievement';
  },
  comment: function(type) {
    return type === 'comment';
  },
  reply: function(type) {
    return type === 'comment';
  },
  isRevision: function(type) {
    return type === 'revision';
  },
  your: function() {
    var c;
    c = Collections[this.targetType].findOne(this.target);
    if (c && c.user === Meteor.user()._id) {
      return 'your';
    }
    return '';
  }
});
