// Generated by CoffeeScript 1.3.3

_.extend(Template.progress, {
  progress: function() {
    var next, user;
    user = Meteor.user();
    if (user && !user.loading) {
      next = Template.body.nextLevel(user.level);
      return 100 * user.score / next;
    }
  },
  progressText: function() {
    var next, user;
    user = Meteor.user();
    if (user && user.score) {
      next = Template.body.nextLevel(user.level);
      return "" + user.score + "/" + next;
    }
  }
});
