// Generated by CoffeeScript 1.3.3

_.extend(Template.progress, {
  progress: function() {
    var inLevelScore, next, user;
    user = Meteor.user();
    if (user && user.score && user.level) {
      next = nextLevel(user.level);
      inLevelScore = user.score - prevLevels(user.level);
      inLevelScore = inLevelScore < 0 ? 0 : inLevelScore;
      return 100 * inLevelScore / next;
    }
  },
  progressText: function() {
    var inLevelScore, next, user;
    user = Meteor.user();
    if (user && user.score && user.level) {
      next = nextLevel(user.level);
      inLevelScore = user.score - prevLevels(user.level);
      inLevelScore = inLevelScore < 0 ? 0 : inLevelScore;
      return "" + inLevelScore + "/" + next;
    }
  }
});
