// Generated by CoffeeScript 1.3.3

_.extend(Template.revisions, {
  events: {
    'click .restore': function(e) {
      return Meteor.call('restore', this);
    }
  },
  revisions: function() {
    var revisions, test;
    test = Revisions.find({
      entity: this._id
    });
    revisions = Revisions.find({
      entity: this._id
    }, {
      eort: {
        date: -1
      },
      limit: 5 * (Session.get('skip') + 1)
    });
    if (test.count() === 0) {
      return false;
    } else {
      return revisions;
    }
  },
  user: function() {
    return Meteor.users.findOne(this.user);
  },
  tagItems: function() {
    var tagItems,
      _this = this;
    tagItems = [];
    _.each(this.tags.added, function(tag) {
      return tagItems.push({
        tag: "- " + tag,
        entity: _this._id,
        entityType: _this.type
      });
    });
    _.each(this.tags.removed, function(tag) {
      return tagItems.push({
        tag: "+ " + tag,
        entity: _this._id,
        entityType: _this.type
      });
    });
    return tagItems;
  }
});
