// Generated by CoffeeScript 1.3.3

_.extend(Template.userBanner, {
  events: {
    'click .refresh': function(e) {
      return Meteor.call('updateUserScoreComplete');
    }
  },
  user: function() {
    var username;
    username = Session.get('username');
    if (username) {
      return Meteor.users.findOne({
        username: username
      });
    }
  },
  pic: function() {
    var username;
    username = Session.get('username');
    if (username) {
      return "<img src='https://graph.facebook.com/" + username + "/picture?type=normal'/>";
    }
  }
});
