// Generated by CoffeeScript 1.3.3

Template.user.helpers({
  user: function() {
    if (this.type === 'user') {
      return this;
    } else if (this.user) {
      return Meteor.users.findOne(this.user);
    }
  }
});
