// Generated by CoffeeScript 1.3.3

_.extend(Template.voteContainer, {
  events: {
    'click .vote': function(e) {
      var $t, data, up;
      if (!e.isPropagationStopped()) {
        e.stopPropagation();
        $t = $(e.target).closest('.vote');
        up = $t.data('up');
        data = {
          entity: this._id,
          entityType: this.type,
          up: up
        };
        return Meteor.call('vote', data);
      }
    }
  },
  voted: function(state) {
    var vote;
    state = state === 'up' ? true : false;
    if (Meteor.user()) {
      vote = Votes.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
      if (vote && vote.up === state) {
        return 'active';
      }
    }
    return '';
  }
});
