// Generated by CoffeeScript 1.3.3

_.extend(Template.miniAccomplishment, Template.accomplishment, {
  events: {
    'click .add-tag': function(e) {
      Session.set('addingTag', this._id);
      Meteor.flush();
      return focusById('addingTag-' + this._id);
    }
  },
  achievement: function() {
    var sel;
    sel = {};
    sel._id = this.entity;
    if (Session.get('category') != null) {
      sel.category = Session.get('category');
    }
    return Achievements.findOne(sel);
  },
  numComments: function() {
    return this.comments;
  }
});
