// Generated by CoffeeScript 1.3.3

_.extend(Template.newAchievement, Template.edit, {
  newAchievement: function() {
    var id;
    id = Session.get('single');
    return Scratchpad.findOne(id);
  }
});

Template.newAchievement.events = _.extend({}, Template.edit.events, {
  'click .close': function(e) {
    return Session.set('styleGuide', true);
  },
  'change .lazy': function(e) {
    var $t, data, field;
    data = {};
    $t = $(e.currentTarget);
    field = $t.data('field');
    data[field] = $t.val();
    return Scratchpad.update(this._id, {
      $set: data
    });
  },
  'click .create': function(e) {
    var data;
    data = Scratchpad.findOne(this._id);
    Meteor.call('newAchievement', data, function(error, result) {
      return window.Router.navigate("achievements/" + result, true);
    });
    return Scratchpad.remove(this._id);
  }
});
