// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplishments, {
    accomplishments: function() {
      var data, sort;
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            score: -1
          };
          break;
        case 'cool':
          data = {
            score: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            score: -1
          };
          break;
        case 'wort':
          data = {
            score: 1
          };
      }
      return Accomplishments.find({
        user: Meteor.user()._id
      }, {
        sort: data
      });
    }
  });

}).call(this);
