// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplish, {
    events: {
      'click .create': function(e) {
        var stry;
        stry = $("#accomplish-" + this._id).val();
        Meteor.call('accomplish', this._id, stry);
        return Session.set('expand', null);
      }
    },
    accomplishment: function() {
      return Accomplishments.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
    }
  });

}).call(this);
