// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplish, {
    events: {
      'click .create': function(e) {
        var acc, stry;
        stry = $("#accomplish-" + this._id).val();
        acc = Accomplishments.findOne({
          user: Meteor.user()._id,
          entity: this._id
        });
        if (acc) {
          Accomplishments.update(acc._id, {
            $set: {
              story: stry
            }
          });
        } else {
          Accomplishments.insert({
            user: Meteor.user()._id,
            entity: this._id,
            story: stry
          });
        }
        return Session.set('expand', null);
      }
    },
    accomplishment: function() {
      return Accomplishments.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
    }
  });

}).call(this);
