// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplishActivityModal, {
    events: {
      'click .save-activity': function(e) {
        var data, draft;
        data = {
          user: Session.get('user'),
          activity: Session.get('activity'),
          text: $('.accomplish-text').val(),
          handedIn: false
        };
        draft = Drafts.findOne({
          user: Session.get('user'),
          activity: Session.get('activity')
        });
        if (draft != null) {
          if (data.text !== '') {
            Drafts.update(draft._id, {
              $set: data
            });
          } else {
            Drafts.remove(draft._id);
          }
        } else {
          Drafts.insert(data);
        }
        return $('.accomplish-modal').modal('hide');
      },
      'click .hand-in-activity': function(e) {
        var draft;
        draft = Drafts.findOne({
          user: Session.get('user'),
          activity: Session.get('activity')
        });
        Drafts.update(draft, {
          $set: {
            handedIn: true
          }
        });
        return $('.accomplish-modal').modal('hide');
      }
    },
    draft: function() {
      var draft;
      draft = Drafts.findOne({
        user: Session.get('user'),
        activity: Session.get('activity')
      });
      return draft || {};
    }
  });

}).call(this);
