// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.achievement, {
    events: {
      'click .vote': function(e) {
        var $t, up;
        if (!e.isPropagationStopped()) {
          $t = $(e.target);
          if (!$t.hasClass('vote')) {
            $t = $t.parents('.vote');
          }
          up = $t.data('up');
          Meteor.call('vote', 'achievements', this._id, up);
          return e.stopPropagation();
        }
      },
      'click .expand': function(e) {
        return Session.toggle('expand', this._id);
      },
      'click .fav': function(e) {
        var fav;
        fav = Favourites.findOne({
          user: Meteor.user()._id,
          entity: this._id
        });
        if (fav) {
          return Favourites.update(fav._id, {
            $set: {
              active: !fav.active
            }
          });
        } else {
          return Favourites.insert({
            user: Meteor.user()._id,
            entity: this._id,
            active: true
          });
        }
      }
    },
    faved: function() {
      var fav;
      if (Meteor.user()) {
        fav = Favourites.findOne({
          user: Meteor.user()._id,
          entity: this._id,
          active: true
        });
        if (fav) {
          return 'active';
        }
      }
      return '';
    },
    voted: function(state) {
      var vote;
      state = state === 'up' ? true : false;
      if (Meteor.user()) {
        vote = Votes.findOne({
          user: Meteor.user()._id,
          entity: this._id
        });
        if (vote && vote.up === state) {
          return 'active';
        }
      }
      return '';
    },
    color: function() {
      var acc, fav;
      if (Session.equals('newAchievement', this._id)) {
        return '';
      }
      acc = Accomplishments.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
      if (acc) {
        return 'completed';
      }
      fav = Favourites.findOne({
        user: Meteor.user()._id,
        entity: this._id,
        active: true
      });
      if (fav) {
        return 'accepted';
      } else if (Session.get('accomplishmentsLoaded')) {
        return 'uncompleted';
      }
      return '';
    }
  });

}).call(this);
