// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.achievements, {
    events: {
      'click .new': function(e) {
        Session.toggle('expand', this._id);
        return Session.set('expandTab', 'edit');
      }
    },
    select: function() {
      var sel;
      sel = {};
      sel.created = true;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      return sel;
    },
    achievements: function() {
      var sel;
      sel = Template.achievements.select();
      return Achievements.find(sel, {
        sort: {
          score: -1,
          _id: -1
        }
      });
    },
    newAchievement: function() {
      var id;
      id = Session.get('newAchievement');
      return Achievements.findOne(id);
    },
    noContent: function() {
      var sel;
      if (Session.equals('achievementsLoaded', true)) {
        sel = Template.achievements.select();
        return Achievements.find(sel).count() === 0;
      }
      return false;
    }
  });

}).call(this);
