// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.activities, {
    events: {
      'click #create .open': function(e) {
        return window.Router.navigate('activities/new', true);
      },
      'click .btn-filter': function(e) {
        var filter, which;
        Session.set('tagFilter', null);
        filter = $(e.target).data('filter');
        which = $(e.target).data('which');
        if (Session.get("activity-filter-" + which) === filter) {
          return Session.set("activity-filter-" + which, null);
        } else {
          return Session.set("activity-filter-" + which, filter);
        }
      }
    },
    activities: function() {
      var sel;
      sel = Template.activities.select();
      if (Session.get('tagFilter')) {
        sel.tags = Session.get('tagFilter');
      }
      return Activities.find(sel, {
        sort: {
          score: -1,
          name: 1
        }
      });
    },
    select: function() {
      var drafts, sel;
      sel = {};
      if (Session.equals('activity-filter-1', 'my')) {
        sel.user = Session.get('user');
      } else if (Session.equals('activity-filter-1', 'lva')) {
        sel.user = {
          $lt: 2000000
        };
      }
      if (Session.equals('activity-filter-2', 'fav')) {
        sel.likes = Session.get('user');
      } else if (Session.equals('activity-filter-2', 'voted')) {
        sel.votes = Session.get('user');
      } else if (Session.equals('activity-filter-2', 'saved')) {
        drafts = Drafts.find({
          user: Session.get('user'),
          handedIn: false
        }).map(function(draft) {
          return draft.activity;
        });
        sel._id = {
          $in: drafts
        };
      } else if (Session.equals('activity-filter-2', 'pending')) {
        drafts = Drafts.find({
          user: Session.get('user'),
          handedIn: true
        }).map(function(draft) {
          return draft.activity;
        });
        sel._id = {
          $in: drafts
        };
      } else if (Session.equals('activity-filter-2', 'done')) {
        sel = null;
      }
      return sel;
    },
    noContent: function() {
      var sel;
      if (Session.equals('activitiesLoaded', true)) {
        sel = Template.activities.select();
        return Activities.find(sel).count() === 0;
      }
      return false;
    }
  });

}).call(this);
