// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.comments, {
    events: {
      'keyup .comment-text, keydown .comment-text, \
     keyup .edit-text, keydown .edit-text': window.makeOkCancelHandler({
        ok: function(text, e) {
          if (Session.get('add-comment') !== null) {
            Comments.insert({
              text: text,
              date: new Date,
              topic: Session.get('expand'),
              parent: Session.get('thread'),
              mention: this.user,
              user: Meteor.user()._id
            });
          } else if (Session.equals('edit-comment', this._id)) {
            Comments.update(this._id, {
              $set: {
                text: text
              }
            });
          }
          Session.set('add-comment', null);
          Session.set('edit-comment', null);
          return e.target.value = "";
        }
      })
    },
    select: function(id) {
      var sel;
      sel = {
        topic: Session.get('expand'),
        parent: null
      };
      if (id) {
        sel.parent = id;
      } else {
        if (Session.equals('comment-filter', 'my')) {
          sel.user = Session.get('user');
        } else if (Session.equals('comment-filter', 'lva')) {
          sel.user = {
            $lt: 2000000
          };
        }
      }
      return sel;
    },
    comments: function() {
      var sel;
      sel = Template.comments.select();
      return Comments.find(sel, {
        sort: {
          date: -1
        }
      });
    },
    replies: function() {
      var sel;
      sel = Template.comments.select(this._id);
      return Comments.find(sel, {
        sort: {
          date: 1
        }
      });
    },
    noContent: function() {
      var sel;
      console.log('tasdf<');
      if (Session.equals('commentsLoaded', true)) {
        sel = Template.comments.select();
        return Comments.find(sel).count() === 0;
      }
      return false;
    }
  });

}).call(this);
