// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.comment, {
    events: {
      'click .reply': function(e) {
        Session.set('add-comment', this._id);
        Session.set('edit-comment', null);
        Session.set('thread', window.getThreadId(this));
        Meteor.flush();
        return window.focusById("reply-" + this._id);
      },
      'click .like': function(e) {
        return Comments.update(this._id, {
          $push: {
            likes: Session.get('user')
          }
        });
      },
      'click .unlike': function(e) {
        return Comments.update(this._id, {
          $pull: {
            likes: Session.get('user')
          }
        });
      },
      'click .edit': function(e) {
        Session.set('add-comment', null);
        Session.set('edit-comment', this._id);
        Session.set('thread', window.getThreadId(this));
        Meteor.flush();
        return window.focusById("reply-" + this._id);
      },
      'click .remove': function(e) {
        return Comments.remove(this._id);
      }
    },
    addComment: function() {
      return Session.equals('add-comment', this._id);
    },
    editComment: function() {
      return Session.equals('edit-comment', this._id);
    },
    formatDate: function(date) {
      var d;
      d = moment(new Date(this.date));
      return d.format("DD.MM.YYYY, hh:mm");
    },
    likesNum: function() {
      if (this.likes != null) {
        return this.likes.length;
      } else {
        return 0;
      }
    },
    nested: function() {
      if (this.parent) {
        return 'nested';
      } else {
        return '';
      }
    },
    addLineBreaks: function(text) {
      text = _.escape(text);
      return text.replace('\n', '<br>');
    },
    mention: function() {
      if (this.mention !== null) {
        return "@" + (window.getUsername(this.mention)) + ":";
      }
    }
  });

}).call(this);
