// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.createActivityModal, {
    events: {
      'click .create-activity': function(e) {
        var data, name, tags, url;
        name = $('.activity-name').val();
        url = encodeURIComponent((name.toLowerCase()).replace(/\s/g, '-'));
        tags = window.findTags($('.description-short').val());
        _.each(this.tags, function(x) {
          if (!_.contains(tags, x)) {
            return tags.push(x);
          }
        });
        data = {
          name: name,
          short: $('.description-short').val(),
          full: $('.description-full').val(),
          user: Session.get('user'),
          tags: tags,
          url: url
        };
        if (Session.get('activity')) {
          Activities.update(this._id, {
            $set: data
          });
        } else {
          data.score = 0;
          Activities.insert(data);
        }
        $('.create-modal').modal('hide');
        return $('.activity-name, .description-short, .description-full').clear();
      }
    },
    title: function() {
      var activityId;
      activityId = Session.get('activity');
      if (activityId) {
        return this.name;
      } else {
        return 'Create New Activity';
      }
    }
  });

}).call(this);
