// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.dashboard, {
    events: {
      'click .add-comment': function(e) {
        Session.set('add-comment', 0);
        return Session.set('edit-comment', null);
      },
      'click .btn-filter': function(e) {
        var filter;
        filter = $(e.target).data('filter');
        if (filter) {
          if (Session.get('comment-filter') === filter) {
            return Session.set('comment-filter', null);
          } else {
            return Session.set('comment-filter', filter);
          }
        }
      },
      'keyup .comment-text,  keydown .comment-text': window.makeOkCancelHandler({
        ok: function(text, e) {
          Comments.insert({
            text: text,
            date: new Date,
            topic: Session.get('expand'),
            parent: null,
            mention: null,
            user: Meteor.user()._id
          });
          Session.set('add-comment', null);
          Session.set('edit-comment', null);
          return e.target.value = "";
        }
      })
    },
    addComment: function() {
      return Session.equals('add-comment', 0);
    }
  });

}).call(this);
