// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.editAchievement, {
    events: {
      'click .close': function(e) {
        return Session.set('styleGuide', false);
      },
      'click .discard': function(e) {
        return Session.toggle('expand', this._id);
      },
      'click .suggest': function(e) {
        var title;
        title = $("#title-" + this._id).val();
        return Titles.insert({
          entity: this._id,
          title: title,
          user: Meteor.user()._id,
          score: 0
        });
      },
      'change .category': function(e) {
        return Achievements.update(this._id, {
          $set: {
            category: $("#category-" + this._id).val()
          }
        });
      },
      'change .description': function(e) {
        var description, tags;
        description = $("#description-" + this._id).val();
        tags = window.findTags(description);
        return Achievements.update(this._id, {
          $set: {
            description: description,
            tags: tags
          }
        });
      },
      'click .create': function(e) {
        var id;
        Achievements.update(this._id, {
          $set: {
            created: true
          }
        });
        id = createNewAchievement();
        Session.set('newAchievement', id);
        return Session.set('expand', null);
      }
    },
    selected: function(category) {
      if (category) {
        if (category === this.name) {
          return 'selected';
        } else {
          return '';
        }
      } else {
        if ('Random' === this.name) {
          return 'selected';
        } else {
          return '';
        }
      }
    }
  });

}).call(this);
