// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.expand, {
    events: {
      'click .tab': function(e) {
        var href, tab;
        tab = $(e.target).data('tab');
        Session.set('tab', tab);
        if (e.which === 1) {
          e.preventDefault();
          href = $(e.target).attr('href');
          if (href) {
            return window.Router.navigate(href, true);
          }
        }
      }
    }
  });

}).call(this);
