// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.expandAchievement, {
    events: {
      'click .tab': function(e) {
        var tab;
        tab = $(e.target).data('tab');
        return Session.set('expandTab', tab);
      }
    }
  });

}).call(this);
