// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.filter, {
    events: {
      'change .sort': function(e) {
        var $t;
        $t = $(e.target).closest('.sort');
        return Session.set('sort', $t.find(':selected').val());
      }
    }
  });

}).call(this);
