// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.home, {
    accomplishments: function() {
      return Accomplishments.find({
        story: {
          $ne: ''
        }
      }, {
        sort: {
          date: -1,
          _id: -1
        }
      });
    }
  });

}).call(this);
