// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.menu, {
    user: function() {
      var username;
      username = Session.get('username');
      if (username) {
        return Meteor.users.findOne({
          username: username
        });
      }
    }
  });

}).call(this);
