// Generated by CoffeeScript 1.3.3

_.extend(Template.miniQuestLog, Template.questLog, {
  favourites: function() {
    var sort, user;
    sort = Template.filter.sort();
    if ((user = Meteor.user())) {
      return Favourites.find({
        user: user._id,
        active: true,
        $where: function() {
          return !Accomplishments.findOne({
            user: user._id,
            entity: this.entity
          });
        }
      }, {
        sort: sort
      });
    }
  }
});
