// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.tagFilter, {
    events: {
      'click .tag': function(e) {
        if (Session.equals('tagFilter', this.tag)) {
          return Session.set('tagFilter', null);
        } else {
          return Session.set('tagFilter', this.tag);
        }
      }
    },
    tags: function() {
      var entities, sel, tagInfos;
      if (Session.equals('page', 'activities')) {
        sel = Template.activities.select();
        entities = Activities.find(sel);
      } else if (Session.equals('page', 'slides')) {
        sel = Template.slideshows.select();
        entities = Slideshows.find(sel);
      }
      tagInfos = [];
      entities.forEach(function(activity) {
        return _.each(activity.tags, function(tag) {
          var tagInfo;
          tagInfo = _.find(tagInfos, function(x) {
            return x.tag === tag;
          });
          if (!tagInfo) {
            return tagInfos.push({
              tag: tag,
              count: 1
            });
          } else {
            return tagInfo.count++;
          }
        });
      });
      tagInfos = _.sortBy(tagInfos, function(x) {
        return x.tag;
      });
      return tagInfos;
    }
  });

}).call(this);
