// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.timeline, {
    accomplishments: function() {
      return Accomplishments.find({
        user: Meteor.user()._id
      });
    },
    achievement: function() {
      return Achievements.findOne(this.entity);
    }
  });

}).call(this);
