// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.titleSuggestions, {
    events: {
      'click .vote': function(e) {
        var $t, up;
        if (!e.isPropagationStopped()) {
          $t = $(e.target);
          if (!$t.hasClass('vote')) {
            $t = $t.parents('.vote');
          }
          up = $t.data('up');
          Meteor.call('vote', 'titles', this._id, up);
          return e.stopPropagation();
        }
      }
    },
    titles: function() {
      var id, titles;
      id = Session.get('single');
      titles = Titles.find({
        entity: id,
        user: Meteor.user()._id
      }, {
        sort: {
          score: -1
        }
      });
      return titles;
    },
    hasTitles: function() {
      var id, titles;
      id = Session.get('single');
      titles = Titles.find({
        entity: id,
        user: Meteor.user()._id
      });
      return titles.count();
    },
    voted: function(state) {
      var vote;
      state = state === "up" ? true : false;
      vote = Votes.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
      if (vote && vote.up === state) {
        return 'active';
      }
      return '';
    }
  });

}).call(this);
