// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.titleSuggestions, {
    events: {
      'click .vote': function(e) {
        var $t, achievementId, data, vote;
        $t = $(e.target);
        data = {
          user: Meteor.user()._id,
          entity: this._id,
          up: $t.data('up')
        };
        vote = Votes.findOne({
          user: Meteor.user()._id,
          entity: this._id
        });
        if (vote) {
          Votes.update(vote._id, {
            $set: data
          });
        } else {
          Votes.insert(data);
        }
        achievementId = Session.get('expand');
        return Meteor.call('updateTitleScore', this._id, achievementId);
      }
    },
    titles: function() {
      var id, titles;
      id = Session.get('expand');
      titles = Titles.find({
        entity: id,
        user: Meteor.user()._id
      }, {
        sort: {
          score: -1
        }
      });
      return titles;
    },
    voted: function(state) {
      var vote;
      state = state === "up" ? true : false;
      vote = Votes.findOne({
        user: Meteor.user()._id,
        entity: this._id
      });
      if (vote && vote.up === state) {
        return 'active';
      }
      return '';
    }
  });

}).call(this);
