// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.userBanner, {
    pic: function() {
      var fbid, user;
      user = Meteor.user();
      if (user) {
        if (user.services) {
          fbid = _.escape(user.services.facebook.id);
          return "<img src='https://graph.facebook.com/" + fbid + "/picture&type=normal'/>";
        }
      }
    }
  });

}).call(this);
