// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.user, {
    verb: function() {
      console.log(this);
      return 'accomplished';
    },
    user: function() {
      return this;
    }
  });

}).call(this);
