// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.userWidget, {
    events: {
      'click .edit': function(e) {
        var value;
        value = Session.get('editUsername');
        Session.set('editUsername', !value);
        Meteor.flush();
        return $('#user-name').focus();
      },
      'keyup #user-name, keydown #user-name': window.makeOkCancelHandler({
        ok: function(text, e) {
          text = text.replace(/\s/g, '');
          Ushers.update(this._id, {
            name: text
          });
          return Session.set('editUsername', false);
        }
      })
    },
    user: function() {
      return Ushers.findOne(Session.get('user'));
    },
    editUsername: function() {
      return Session.equals('editUsername', true);
    }
  });

}).call(this);
