// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone.sync = function(method, model, options) {
    var collection;
    options || (options = {});
    if (!model.url) {
      throw new Error('whatever');
    }
    collection = Collections[model.url];
    if (!collection) {
      throw new Error('whatever');
    }
    switch (methods) {
      case 'create':
        return collection.insert(model.toJSON());
      case 'update':
        return collection.update(model.id, model.toJSON());
      case 'delete':
        return collection.remove(model.id);
      case 'read':
        return collection.findOne(model.id);
    }
  };

  Meteor.Model = (function(_super) {

    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.idAttribute = '_id';

    return Model;

  })(Backbone.Model);

}).call(this);
