// Generated by CoffeeScript 1.3.3

Backbone.sync = function(method, model, options) {
  var attrs, collection, id;
  options || (options = {});
  if (!(collection = Collections[model.type])) {
    throw new Error('whatever');
  }
  switch (method) {
    case 'create':
      id = collection.insert(model.toJSON());
      attrs = collection.findOne(id);
      if (attrs) {
        return options.success(attrs);
      } else {
        return options.error(model);
      }
      break;
    case 'update':
      collection.update(model.id, model.toJSON());
      return options.success(model);
    case 'delete':
      collection.remove(model.id);
      return options.success();
    case 'read':
      attrs = collection.findOne(model.id);
      if (attrs) {
        return options.success(attrs);
      } else {
        return options.error(model);
      }
  }
};
