// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplishments, {
    select: function() {
      var sel;
      sel = {};
      if (Session.get('tagFilter') != null) {
        sel.tags = Session.get('tagFilter');
      }
      return sel;
    },
    accomplishments: function() {
      var sel, sort, user, username;
      sort = Template.filter.sort();
      username = Session.get('username');
      if (username) {
        user = Meteor.users.findOne({
          username: username
        });
        if (user) {
          sel = Template.accomplishments.select();
          _.extend(sel, {
            user: user._id
          });
          return Accomplishments.find(sel, {
            sort: sort
          });
        }
      }
    }
  });

}).call(this);
