// Generated by CoffeeScript 1.3.3

_.extend(Template.accomplish, {
  events: {
    'click .create': function(e) {
      var data, story;
      if (!e.isPropagationStopped()) {
        e.stopPropagation();
        story = $("#editor-" + this._id).val();
        this.tags || (this.tags = []);
        data = {
          entity: this._id,
          entityType: 'achievement',
          story: story,
          tags: this.tags
        };
        Meteor.call('accomplish', data, function(error, result) {
          return window.Router.navigate("/accomplishments/" + result, true);
        });
        return Session.set('modal', this._id);
      }
    },
    'click .uncreate': function(e) {
      return Accomplishments.remove(this._id);
    },
    'click a.editor': function(e) {
      $('.editor').hide();
      return $('.preview').show();
    },
    'click a.preview': function(e) {
      $('.editor').show();
      return $('.preview').hide();
    }
  },
  accomplishment: function() {
    return Accomplishments.findOne({
      user: Meteor.user()._id,
      entity: this._id
    });
  },
  story: function() {
    var acpl;
    acpl = Accomplishments.findOne({
      user: Meteor.user()._id,
      entity: this._id
    });
    if (acpl) {
      if (acpl.story) {
        return acpl.story;
      }
    }
    return '';
  },
  callback: function() {
    var _this = this;
    Meteor.setTimeout(function() {
      return $("#editor-" + _this._id).markdownEditor({
        toolbarLoc: $("#toolbar-" + _this._id),
        toolbar: "default",
        preview: $("#preview-" + _this._id)
      });
    }, 0);
    return '';
  }
});
