// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplishments, {
    accomplishments: function() {
      var sort, user, username;
      sort = Template.filter.sort();
      username = Session.get('username');
      if (username) {
        user = Meteor.users.findOne({
          username: username
        });
        if (user) {
          return Accomplishments.find({
            user: user._id
          }, {
            sort: sort
          });
        }
      }
    }
  });

}).call(this);
