// Generated by CoffeeScript 1.3.3

_.extend(Template.accomplishments, {
  select: function() {
    var sel;
    sel = {};
    if (Session.get('tagFilter') != null) {
      Session.get('_tagFilter');
      sel.tags = {
        $all: Session.get('tagFilter')
      };
    }
    switch (Session.get('limit')) {
      case 'me':
        sel.user = Meteor.user()._id;
        break;
      case 'friends':
        sel.user = {
          $in: [Meteor.user()._id]
        };
    }
    return sel;
  },
  accomplishments: function() {
    var sel, sort, user, username;
    username = Session.get('username');
    if (username) {
      user = Meteor.users.findOne({
        username: username
      });
      if (user) {
        sel = Template.accomplishments.select();
        _.extend(sel, {
          user: user._id
        });
        sort = Template.filter.sort();
        return Accomplishments.find(sel, {
          sort: sort
        });
      }
    }
  }
});
