// Generated by CoffeeScript 1.3.3

_.extend(Template.achievements, {
  achievements: function() {
    var sel, sort;
    sort = Template.filter.sort();
    sel = Template.filter.select();
    sel.created = true;
    return Achievements.find(sel, {
      sort: sort
    });
  }
});
