// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.achievements, {
    select: function() {
      var sel;
      sel = {};
      sel.created = true;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      if (Session.get('tagFilter') != null) {
        Session.get('_tagFilter');
        sel.tags = {
          $all: Session.get('tagFilter')
        };
      }
      switch (Session.get('limit')) {
        case 'me':
          sel.user = Meteor.user()._id;
          break;
        case 'friends':
          sel.user = {
            $in: [Meteor.user()._id]
          };
      }
      return sel;
    },
    achievements: function() {
      var a, sel, sort;
      sel = Template.achievements.select();
      sort = Template.filter.sort();
      a = Achievements.find(sel, {
        sort: sort
      });
      return a;
    }
  });

}).call(this);
