// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.body, {
    events: {
      'click a[href^="/"]': function(e) {
        var $t, href;
        if (e.which === 1 && !(e.ctrlKey || e.metaKey)) {
          e.preventDefault();
          $t = $(e.target).closest('a[href^="/"]');
          href = $t.attr('href');
          if (href) {
            return window.Router.navigate(href, true);
          }
        }
      }
    },
    nextLevel: function(level) {
      var next;
      next = 0;
      switch (level) {
        case 1:
          next = 10;
          break;
        case 2:
          next = 25;
          break;
        case 3:
          next = 125;
          break;
        case 4:
          next = 525;
          break;
        case 5:
          next = 1225;
      }
      return next;
    },
    progress: function() {
      var next, user;
      user = Meteor.user();
      if (user && !user.loading) {
        next = Template.body.nextLevel(user.level);
        return 100 * user.score / next;
      }
    },
    progressText: function() {
      var next, user;
      user = Meteor.user();
      if (user && !user.loading) {
        next = Template.body.nextLevel(user.level);
        return "" + user.score + "/" + next;
      }
    }
  });

}).call(this);
