// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.edit, Template.vote, {
    events: {
      'click .close': function(e) {
        return Session.set('styleGuide', true);
      },
      'click .discard': function(e) {
        return Session.toggle('expand', this._id);
      },
      'click .suggest': function(e) {
        var data, id, title;
        title = $("#title-" + this._id).val();
        data = {
          title: title,
          type: 'title',
          entity: this._id,
          user: Meteor.user()._id,
          score: 0
        };
        id = Titles.insert(data);
        _.extend(data, {
          _id: id
        });
        return Meteor.call('assignBestTitle', data);
      },
      'change .category': function(e) {
        return this.category = $("#category-" + this._id).val();
      },
      'change .description': function(e) {
        var description, tags;
        description = $("#description-" + this._id).val();
        tags = window.findTags(description);
        this.description = description;
        return this.tags = tags;
      },
      'click .create': function(e) {
        var data;
        data = {};
        $("#form-" + this._id).find('.lazy').each(function() {
          var $t, field;
          $t = $(this);
          field = $t.data('field');
          if (field != null) {
            return data[field] = $t.val();
          }
        });
        data.created = true;
        Achievements.update(this._id, {
          $set: data
        });
        return Session.set('newAchievement', null);
      }
    },
    selected: function(category) {
      if (category) {
        if (category === this.name) {
          return 'selected';
        } else {
          return '';
        }
      } else if (Session.get('category') != null) {
        if (Session.get('category') === this.name) {
          return 'selected';
        } else {
          return '';
        }
      } else {
        if ('Random' === this.name) {
          return 'selected';
        } else {
          return '';
        }
      }
    },
    titles: function() {
      var id, titles;
      id = Session.get('single');
      titles = Titles.find({
        entity: id,
        user: Meteor.user()._id
      }, {
        sort: {
          score: -1
        }
      });
      return titles;
    },
    hasTitles: function() {
      var id, titles;
      id = Session.get('single');
      titles = Titles.find({
        entity: id,
        user: Meteor.user()._id
      });
      return titles.count();
    }
  });

  _.extend(Template.edit.events, Template.vote.events);

}).call(this);
