// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.favourites, {
    favourites: function() {
      var sort, user, username;
      sort = Template.filter.sort();
      username = Session.get('username');
      if (username) {
        user = Meteor.users.findOne({
          username: username
        });
        if (user) {
          return Favourites.find({
            user: user._id,
            active: true
          }, {
            sort: sort
          });
        }
      }
    },
    achievement: function() {
      var sel;
      sel = {};
      sel._id = this.entity;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      return Achievements.findOne(sel);
    }
  });

}).call(this);
