// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.filter, {
    events: {
      'change .sort': function(e) {
        var $t;
        $t = $(e.target).closest('.sort');
        return Session.set('sort', $t.find(':selected').val());
      },
      'click .tab': function(e) {
        var $t;
        $t = $(e.target).closest('.tab');
        return Session.set('limit', $t.data('tab'));
      }
    },
    sort: function() {
      var data, sort;
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            hot: -1
          };
          break;
        case 'cool':
          data = {
            hot: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            best: -1
          };
          break;
        case 'worst':
          data = {
            best: 1
          };
      }
      return data;
    },
    limit: function() {}
  });

}).call(this);
