// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.filter, {
    events: {
      'change .sort': function(e) {
        var $t;
        $t = $(e.currentTarget);
        return Session.set('sort', $t.find(':selected').val());
      },
      'click .tab': function(e) {
        var $t;
        $t = $(e.currentTarget);
        return Session.set('limit', $t.data('tab'));
      },
      'keyup .search-query,  keydown .search-query': makeOkCancelHandler({
        ok: function(text, e) {
          var tags;
          $(e.currentTarget).blur();
          tags = window.findTags(text);
          if (tags && _.size(tags) > 0) {
            return Session.set('tagFilter', tags);
          } else {
            return Session.set('tagFilter', null);
          }
        },
        cancel: function(e) {
          $(e.currentTarget).blur();
          return Session.set('tagFilter', null);
        }
      })
    },
    sort: function() {
      var data, sort;
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            hot: -1
          };
          break;
        case 'cool':
          data = {
            hot: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            best: -1
          };
          break;
        case 'worst':
          data = {
            best: 1
          };
      }
      return data;
    },
    limit: function() {},
    query: function() {
      var tags;
      Session.get('_tagFilter');
      tags = Session.get('tagFilter');
      if (tags && _.size(tags) > 0) {
        tags = tags.join(' #');
        return '#' + tags;
      }
    }
  });

}).call(this);
