// Generated by CoffeeScript 1.3.3

_.extend(Template.header, {
  events: {
    'click .category .nav-item': function(e) {
      var $t, category;
      $t = $(e.target).closest('.category');
      category = $t.data('category');
      return Session.set('category', category);
    }
  },
  pic: function() {
    var fbid, user;
    user = Meteor.user();
    if (user) {
      if (user.services) {
        fbid = _.escape(user.services.facebook.id);
        return "<img src='https://graph.facebook.com/" + fbid + "/picture'/>";
      }
    }
  },
  items: function() {
    var item, items, _i, _len;
    items = [
      {
        name: 'Home',
        icon: 'home'
      }, {
        name: 'Explore',
        icon: 'road'
      }, {
        name: 'Ladder',
        icon: 'globe'
      }, {
        name: 'Profile',
        icon: 'user',
        url: Meteor.user().username
      }, {
        name: 'Quest Log',
        icon: 'book',
        url: Meteor.user().username + '/questlog'
      }, {
        name: 'New achievement',
        icon: 'certificate',
        url: 'achievements/new'
      }
    ];
    for (_i = 0, _len = items.length; _i < _len; _i++) {
      item = items[_i];
      if (!item.url) {
        item.url = item.name.toLowerCase();
      }
    }
    return items;
  },
  numNotifications: function() {
    if (Meteor.user()) {
      return Notifications.find({
        receivers: Meteor.user()._id,
        seen: {
          $ne: Meteor.user()._id
        }
      }).count();
    }
  }
});
