// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.home, {
    accomplishments: function() {
      var sel, sort;
      sort = Template.filter.sort();
      sel = Template.accomplishments.select();
      return Accomplishments.find(sel, {
        sort: sort
      });
    }
  });

}).call(this);
