// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.home, {
    accomplishments: function() {
      var sort;
      sort = Template.filter.sort();
      return Accomplishments.find({}, {
        sort: sort
      });
    }
  });

}).call(this);
