// Generated by CoffeeScript 1.3.3

_.extend(Template.notification, {
  user: function() {
    return Meteor.users.findOne(this.user);
  },
  title: function() {
    return this.entityType === 'title';
  },
  vote: function() {
    return this.entityType === 'vote';
  },
  accomplishment: function() {
    return this.entityType === 'accomplishment';
  },
  comment: function() {
    return this.entityType === 'comment';
  },
  your: function() {
    var c;
    c = Collections[this.targetType].findOne(this.target);
    if (c && c.user === Meteor.user()._id) {
      return 'your';
    }
    return '';
  }
});
