// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.notifications, {
    notifications: function() {
      var ret;
      ret = Notifications.find({
        receivers: Meteor.user()._id
      }, {
        sort: {
          date: -1
        }
      });
      Notifications.update({
        receivers: Meteor.user()._id,
        seen: {
          $ne: Meteor.user()._id
        }
      }, {
        $push: {
          seen: Meteor.user()._id
        }
      }, {
        multi: true
      });
      return ret;
    }
  });

}).call(this);
