// Generated by CoffeeScript 1.3.3

_.extend(Template.revisions, {
  events: {
    'click .restore': function(e) {
      return Meteor.call('restore', this);
    }
  },
  revisions: function() {
    var revisions;
    revisions = Revisions.find({
      entity: this._id
    }, {
      sort: {
        date: -1
      }
    });
    if (revisions.count() === 0) {
      return false;
    } else {
      return revisions;
    }
  },
  tagItems: function() {
    var tagItems,
      _this = this;
    tagItems = [];
    _.each(this.tags.added, function(tag) {
      return tagItems.push({
        tag: "- " + tag,
        entity: _this._id,
        entityType: _this.type
      });
    });
    _.each(this.tags.removed, function(tag) {
      return tagItems.push({
        tag: "+ " + tag,
        entity: _this._id,
        entityType: _this.type
      });
    });
    return tagItems;
  }
});
