// Generated by CoffeeScript 1.3.3

_.extend(Template.revisions, {
  revisions: function() {
    return Revisions.find({
      entity: this._id
    }, {
      sort: {
        date: -1
      }
    });
  }
});
