// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.single, {
    achievement: function() {
      var entity, id;
      id = Session.get('single');
      entity = Achievements.findOne(id);
      if (entity) {
        Session.set('topic', entity._id);
        return entity;
      }
    },
    accomplishment: function() {
      var entity, id;
      id = Session.get('single');
      entity = Accomplishments.findOne(id);
      if (entity) {
        Session.set('topic', entity._id);
        return entity;
      }
    },
    comment: function() {
      var entity, id;
      id = Session.get('single');
      entity = Comments.findOne(id);
      if (entity) {
        Session.set('topic', entity.topic);
        Session.set('parent', entity._id);
        Session.set('level', entity.level);
        return entity;
      }
    }
  });

}).call(this);
