// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.single, {
    achievement: function() {
      var entity, id;
      id = Session.get('single');
      entity = Achievements.findOne(id);
      if (entity) {
        Session.set('topic', entity._id);
        Session.set('topicType', entity.type);
        return entity;
      }
    },
    accomplishment: function() {
      var entity, id;
      id = Session.get('single');
      entity = Accomplishments.findOne(id);
      if (entity) {
        Session.set('topic', entity._id);
        Session.set('topicType', entity.type);
        return entity;
      }
    },
    comment: function() {
      var comment, id;
      id = Session.get('single');
      comment = Comments.findOne(id);
      if (comment) {
        Session.set('topic', comment.topic);
        Session.set('topicType', comment.topicType);
        Session.set('parent', comment._id);
        Session.set('level', comment.level);
        return comment;
      }
    }
  });

}).call(this);
