// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.tags, {
    events: {
      'click .add': function(e) {
        Session.set('addingTag', this._id);
        Meteor.flush();
        return focusById('addingTag-' + this._id);
      },
      'keyup .edittag-input,  keydown .edittag-input': makeOkCancelHandler({
        ok: function(text, e) {
          if (!this.tags) {
            this.tags = [];
          }
          text = text.replace(/\s/g, '');
          this.tags = _.union(this.tags, [text]);
          window.table[this.type].update(this._id, {
            $set: {
              tags: this.tags
            }
          });
          return Session.set('addingTag', null);
        },
        cancel: Session.set('addingTag', null)
      }),
      'click .remove': function(e) {
        e.stopPropagation();
        return window.table[this.entityType].update(this.entity, {
          $pull: {
            tags: this.tag
          }
        });
      }
    },
    tagObjects: function() {
      var tagObjects,
        _this = this;
      tagObjects = [];
      _.each(this.tags, function(tag) {
        return tagObjects.push({
          tag: tag,
          entity: _this._id,
          entityType: _this.type
        });
      });
      return tagObjects;
    },
    addingTag: function() {
      Session.get('redraw');
      return Session.equals('addingTag', this._id);
    }
  });

}).call(this);
