// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.tags, {
    events: {
      'click .add': function(e) {
        Session.set('addingTag', this._id);
        Meteor.flush();
        return focusById('addingTag-' + this._id);
      },
      'keyup .edittag-input,  keydown .edittag-input': makeOkCancelHandler({
        ok: function(text, e) {
          if (!this.tags) {
            this.tags = [];
          }
          text = text.replace(/\s/g, '');
          this.tags = _.union(this.tags, [text]);
          return Session.set('addingTag', null);
        },
        cancel: Session.set('addingTag', null)
      })
    },
    addingTag: function() {
      Session.get('redraw');
      return Session.equals('addingTag', this._id);
    },
    tag: function() {
      return this;
    }
  });

}).call(this);
