// Generated by CoffeeScript 1.3.3

_.extend(Template.user, {
  user: function() {
    if (_.isObject(this.user)) {
      return this.user;
    } else {
      return Meteor.users.findOne(this.user);
    }
  }
});
