// Generated by CoffeeScript 1.3.3

_.extend(Template.userActivity, {
  user: function() {
    return Meteor.users.findOne(this.user);
  },
  verb: function() {
    var verb;
    if (this.type === 'accomplishment') {
      verb = 'accomplished';
    }
    if (this.type === 'comment') {
      if (this.parent != null) {
        verb = 'replied';
      } else {
        verb = 'commented';
      }
    }
    return verb;
  }
});
