// Generated by CoffeeScript 1.3.3
var Activities, Quests, Scratchpad;

Scratchpad = new Meteor.Collection(null);

Activities = new Meteor.Collection('activities');

Quests = new Meteor.Collection('quests');
