// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.subscribe('users');

  Meteor.subscribe('comments');

  Meteor.autosubscribe(function() {
    var achievement;
    achievement = Session.get('single');
    if (achievement) {
      return Meteor.subscribe('titles', achievement, function() {});
    }
  });

  Meteor.subscribe('achievements', function() {});

  Meteor.subscribe('votes', function() {});

  Meteor.subscribe('favourites', function() {});

  Meteor.subscribe('accomplishments', function() {});

  Meteor.subscribe('notifications', function() {});

}).call(this);
