// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.accomplishModal, {
    achievement: function() {
      var id;
      id = Session.get('modal');
      if (id) {
        return Achievements.findOne(id);
      }
    },
    callback: function() {
      var _this = this;
      Meteor.setTimeout(function() {
        $('#modal').modal();
        return $('#modal').on('hidden', function() {
          return Session.set('modal', null);
        });
      }, 0);
      return '';
    }
  });

}).call(this);
