// Generated by CoffeeScript 1.3.3

_.extend(Template.accomplishModal, {
  achievement: function() {
    var id;
    id = Session.get('modal');
    if (id) {
      return Achievements.findOne(id);
    }
  },
  rendered: function() {
    var achievement, id;
    id = Session.get('modal');
    if (id) {
      achievement = Achievements.findOne(id);
      if (achievement) {
        $('#modal').modal();
        return $('#modal').on('hidden', function() {
          return Session.set('modal', null);
        });
      }
    }
  }
});
