// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.startup(function() {
    var canModify;
    canModify = function(userId, tasks) {
      return _.all(tasks, function(task) {
        return !task.privateTo || task.privateTo === userId;
      });
    };
    /*
      Todos.allow
        insert: -> return true
        update: canModify
        remove: canModify
        fetch: ['privateTo']
    */

    return Comments.allow({
      insert: function() {
        return true;
      }
    });
  });

}).call(this);
