// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.startup(function() {
    var rank, users;
    users = Meteor.users.find({}, {
      sort: {
        score: -1
      }
    });
    rank = 1;
    users.forEach(function(user) {
      Meteor.users.update(user._id, {
        $set: {
          rank: rank
        }
      });
      return rank++;
    });
    users.observe({
      added: function(user) {
        var options, url,
          _this = this;
        url = "https://graph.facebook.com/" + user.services.facebook.id;
        options = {
          params: {
            access_token: user.services.facebook.accessToken
          }
        };
        return Meteor.http.get(url, options, function(error, res) {
          return Meteor.users.update(user._id, {
            $set: {
              username: res.data.username,
              bio: res.data.bio,
              location: res.data.location.name
            }
          });
        });
      },
      moved: function(user, oldRank, newRank) {
        return Meteor.users.update(user._id, {
          $set: {
            rank: newRank
          }
        });
      }
    });
    return Titles.find().observe({
      changed: function(title) {
        var achievementId, best;
        achievementId = title.entity;
        best = Titles.findOne({
          entity: achievementId
        }, {
          sort: {
            score: -1
          }
        });
        if (best) {
          return Achievements.update(achievementId, {
            $set: {
              title: best.title
            }
          });
        }
      }
    });
  });

}).call(this);
