// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.publish('slideshows', function() {
    return Slideshows.find();
  });

  Meteor.publish('activities', function() {
    return Activities.find();
  });

  Meteor.publish('drafts', function(user) {
    return Drafts.find({
      user: user
    });
  });

  Meteor.publish('ushers', function() {
    return Ushers.find();
  });

  Meteor.publish('slides', function(slideshowId) {
    return Slides.find({
      slideshowId: slideshowId
    });
  });

  Meteor.publish('comments', function(topic) {
    return Comments.find({
      topic: topic
    });
  });

  Meteor.publish('dashboardComments', function() {
    return DashboardComments.find();
  });

}).call(this);
