// Generated by CoffeeScript 1.3.3
(function() {

  Meteor.publish('users', function() {
    return Meteor.users.find();
  });

  Meteor.publish('comments', function() {
    return Comments.find();
  });

  Meteor.publish('achievements', function() {
    return Achievements.find();
  });

  Meteor.publish('titles', function(entity) {
    return Titles.find({
      entity: entity
    });
  });

  Meteor.publish('votes', function() {
    return Votes.find({
      user: this.userId()
    });
  });

  Meteor.publish('favourites', function() {
    return Favourites.find({
      user: this.userId()
    });
  });

  Meteor.publish('accomplishments', function() {
    return Accomplishments.find();
  });

}).call(this);
