// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.achievements, {
    events: {
      'click .new': function(e) {
        Session.toggle('expand', this._id);
        return Session.set('tab', 'edit');
      }
    },
    select: function() {
      var sel;
      sel = {};
      sel.created = true;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      return sel;
    },
    achievements: function() {
      var a, data, sel, sort;
      sel = Template.achievements.select();
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            score: -1
          };
          break;
        case 'cool':
          data = {
            score: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            score: -1
          };
          break;
        case 'wort':
          data = {
            score: 1
          };
      }
      a = Achievements.find(sel, {
        sort: data
      });
      return a;
    },
    newAchievement: function() {
      var id;
      id = Session.get('newAchievement');
      return Achievements.findOne(id);
    }
  });

}).call(this);
