// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.achievements, {
    select: function() {
      var sel;
      sel = {};
      sel.created = true;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      return sel;
    },
    achievements: function() {
      var a, data, sel, sort;
      sel = Template.achievements.select();
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            hot: -1
          };
          break;
        case 'cool':
          data = {
            hot: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            best: -1
          };
          break;
        case 'worst':
          data = {
            best: 1
          };
      }
      a = Achievements.find(sel, {
        sort: data
      });
      return a;
    }
  });

}).call(this);
