// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.comments, {
    events: {
      'click .new': function(e) {
        Session.set('addComment', 'new');
        Meteor.flush();
        return window.focusById("add-" + this._id);
      },
      'keyup .new-thread,  keydown .new-thread': window.makeOkCancelHandler({
        ok: function(text, e) {
          var data;
          data = {
            text: text,
            parent: Session.get('parent'),
            type: Session.get('page'),
            topic: Session.get('topic')
          };
          Meteor.call('comment', data);
          Session.set('addComment', null);
          Session.set('editComment', null);
          return e.target.value = "";
        }
      }),
      'keyup .comment-text, keydown .comment-text': window.makeOkCancelHandler({
        ok: function(text, e) {
          var data;
          if (Session.get('addComment') !== null) {
            data = {
              text: text,
              parent: this._id,
              type: Session.get('page'),
              topic: Session.get('topic')
            };
            Meteor.call('comment', data);
          }
          Session.set('addComment', null);
          Session.set('editComment', null);
          return e.target.value = "";
        }
      }),
      'keyup .edit-text, keydown .edit-text': window.makeOkCancelHandler({
        ok: function(text, e) {
          var data;
          if (Session.equals('editComment', this._id)) {
            data = {
              _id: this._id,
              text: text
            };
            Meteor.call('comment', data);
          }
          Session.set('addComment', null);
          Session.set('editComment', null);
          return e.target.value = "";
        }
      })
    },
    select: function(id) {
      var sel;
      sel = {
        topic: Session.get('topic'),
        parent: Session.get('parent')
      };
      if (id) {
        sel.parent = id;
      }
      if (Session.equals('limit', 'me')) {
        sel.user = Meteor.user()._id;
      }
      if (Session.equals('limit', 'friends')) {
        sel.user = 'hugo';
      }
      return sel;
    },
    comments: function() {
      var c, data, sel, sort;
      sel = Template.comments.select();
      sort = Session.get('sort');
      switch (sort) {
        case 'hot':
          data = {
            hot: -1
          };
          break;
        case 'cool':
          data = {
            hot: 1
          };
          break;
        case 'new':
          data = {
            date: -1
          };
          break;
        case 'old':
          data = {
            date: 1
          };
          break;
        case 'best':
          data = {
            best: -1
          };
          break;
        case 'worst':
          data = {
            best: 1
          };
      }
      c = Comments.find(sel, {
        sort: data
      });
      return c;
    },
    user: function() {
      return Meteor.users.findOne(this.user);
    }
  });

}).call(this);
