// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.miniQuestLog, Template.questLog, {
    favourites: function() {
      var sort, user;
      sort = Template.filter.sort();
      user = Meteor.user();
      if (user) {
        return Favourites.find({
          user: user._id,
          active: true
        }, {
          sort: sort
        });
      }
    }
  });

}).call(this);
