// Generated by CoffeeScript 1.3.3
(function() {

  _.extend(Template.miniQuestLog, Template.favourites, {
    achievement: function() {
      var acc, sel;
      sel = {};
      sel._id = this.entity;
      if (Session.get('category') != null) {
        sel.category = Session.get('category');
      }
      acc = Accomplishments.findOne({
        user: Meteor.user()._id,
        entity: this.entity
      });
      if (acc) {
        return false;
      }
      return Achievements.findOne(sel);
    }
  });

}).call(this);
