// Generated by CoffeeScript 1.3.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Session.toggle = function(name, value) {
    if (value != null) {
      if (Session.equals(name, value)) {
        return Session.set(name, null);
      } else {
        return Session.set(name, value);
      }
    } else {
      return Session.set(name, !Session.get(name));
    }
  };

  window.createNewAchievement = function() {
    var id, newAchievement;
    if (Meteor.user()) {
      newAchievement = Achievements.findOne({
        user: Meteor.user()._id,
        created: false
      });
      if (newAchievement) {
        id = newAchievement._id;
      } else {
        id = Achievements.insert({
          user: Meteor.user()._id,
          score: 0,
          created: false
        });
      }
      return id;
    }
  };

  window.makeOkCancelHandler = function(options) {
    var cancel, ok;
    ok = options.ok || function() {};
    cancel = options.cancel || function() {};
    return function(evt) {
      var value;
      if (evt.type === "keydown" && evt.which === 27) {
        return cancel.call(this, evt);
      } else if (evt.type === "keyup" && evt.which === 13) {
        value = String(evt.target.value || "");
        if (value) {
          return ok.call(this, value, evt);
        } else {
          return cancel.call(this, evt);
        }
      }
    };
  };

  window.getThreadId = function(comment) {
    while (comment.parent !== null) {
      comment = Comments.findOne(comment.parent);
    }
    return comment._id;
  };

  window.focusById = function(id) {
    return $('#' + id).focus().select();
  };

  window.findTags = function(text) {
    var match, pattern, tags;
    pattern = /[^&]\B(#(\w\w+))/g;
    text = _.escape(text);
    tags = [];
    while (match = pattern.exec(text)) {
      tags.push(match[2]);
    }
    return tags;
  };

  window.wrapTags = function(text) {
    var pattern;
    if (text) {
      pattern = /[^&]\B(#(\w\w+))/g;
      text = _.escape(text);
      return text.replace(pattern, ' <a class="tag" data-tag="$2">$1</a>');
    }
    return '';
  };

  $.fn.clear = function() {
    return $(this).val('');
  };

  window.positionActivityModal = function($modal, id) {
    var p;
    if (id != null) {
      p = $('#activity-' + id).offset();
    }
    if (!(id != null) || !(p != null)) {
      p = {};
      p.top = 50;
    }
    $modal.modal({
      keyboard: false,
      show: true
    }).offset({
      top: p.top
    }).on('hide', function() {
      $('body').height('auto');
      return window.Router.navigate('activities', true);
    });
    $('body').height($('body').height() + $(window).height());
    return $(document).scrollTop(p.top - 50);
  };

  window.getUsername = function(userId) {
    var user;
    user = Ushers.findOne(userId);
    if (user) {
      return user.name;
    }
    return '';
  };

  window.softReset = function() {
    $('.modal').modal('hide');
    Session.set('add-comment', null);
    Session.set('edit-comment', null);
    Session.set('topic', 'dashboard');
    Session.set('thread', null);
    Session.set('activity', null);
    return Session.set('addingTag', null);
  };

  window.hardReset = function() {
    window.softReset();
    $(document).scrollTop(0);
    Session.set('comment-filter', null);
    Session.set('activity-filter-1', null);
    Session.set('activity-filter-2', null);
    return Session.set('tagFilter', null);
  };

  Handlebars.registerHelper('show', function(name) {
    return Session.equals(name, true);
  });

  Handlebars.registerHelper('equals', function(name, value) {
    return Session.equals(name, value);
  });

  Handlebars.registerHelper('isActive', function(name, value) {
    if (Session.equals(name, value)) {
      return 'active';
    } else {
      return '';
    }
  });

  Handlebars.registerHelper('belongsTo', function(user) {
    return Session.equals('user', user);
  });

  Handlebars.registerHelper('isMe', function(user) {
    if (Session.equals('user', user)) {
      return 'my';
    } else {
      return '';
    }
  });

  Handlebars.registerHelper('isLva', function(user) {
    if (user <= 2000000) {
      return 'lva';
    } else {
      return '';
    }
  });

  Handlebars.registerHelper('userIn', function(field) {
    var _ref;
    if (field != null) {
      return _ref = Session.get('user'), __indexOf.call(field, _ref) >= 0;
    }
    return false;
  });

  Handlebars.registerHelper('activity', function() {
    var activity, activityId;
    activityId = Session.get('activity');
    activity = Activities.findOne(activityId);
    return activity || {};
  });

  Handlebars.registerHelper('wrapTags', window.wrapTags);

  Handlebars.registerHelper('getUsername', window.getUsername);

  window.items = [
    {
      name: 'Achievements'
    }, {
      name: 'Ladder'
    }
  ];

  window.categories = [
    {
      name: 'Carrier'
    }, {
      name: 'Education'
    }, {
      name: 'Health'
    }, {
      name: 'Meta'
    }, {
      name: 'Random'
    }, {
      name: 'Sports'
    }
  ];

  Handlebars.registerHelper('categories', function() {
    var cat, _i, _len, _ref;
    _ref = window.categories;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cat = _ref[_i];
      if (!cat.url) {
        cat.url = cat.name.toLowerCase();
      }
    }
    return window.categories;
  });

  _.extend(Template.content, {
    page: function(page) {
      return Session.equals('page', page);
    }
  });

  _.extend(Template.header, {
    events: {
      'click .nav-item': function(e) {
        if (e.which === 1) {
          e.preventDefault();
          return window.Router.navigate($(e.target).attr('href'), true);
        }
      }
    },
    items: function() {
      var item, _i, _len, _ref;
      _ref = window.items;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (!item.url) {
          item.url = item.name.toLowerCase();
        }
      }
      return window.items;
    }
  });

}).call(this);
