// Generated by CoffeeScript 1.3.3
(function() {
  var AppRouter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AppRouter = (function(_super) {

    __extends(AppRouter, _super);

    function AppRouter() {
      return AppRouter.__super__.constructor.apply(this, arguments);
    }

    AppRouter.prototype.routes = {
      '': 'default',
      ':menu': 'menu',
      ':user': 'user',
      'achievements/:id': 'achievements',
      'achievements/:id/:tab': 'achievements',
      'accomplishments/:id': 'accomplishments',
      'accomplishments/:id/:tab': 'accomplishments',
      'profile/:menu': 'profile',
      'comments/:id': 'comments'
    };

    AppRouter.prototype["default"] = function() {
      return this.navigate('dashboard', true);
    };

    AppRouter.prototype.menu = function(page) {
      this.hardReset();
      switch (page) {
        case 'dashboard':
          Session.set('sort', 'hot');
          Session.set('page', page);
          return Session.set('limit', 'all');
        case 'achievements':
          Session.set('sort', 'best');
          Session.set('page', page);
          return Session.set('limit', 'all');
        case 'ladder':
          Session.set('sort', 'best');
          Session.set('page', page);
          return Session.set('limit', 'all');
        case 'profile':
          Session.set('sort', 'new');
          Session.set('menu', 'activity');
          Session.set('page', page);
          return Session.set('limit', 'me');
        default:
          Session.set('sort', 'new');
          Session.set('menu', 'activity');
          Session.set('page', 'profile');
          return Session.set('limit', 'me');
      }
    };

    AppRouter.prototype.comments = function(id) {
      var c;
      this.softReset();
      Session.set('parent', id);
      c = Comments.findOne(id);
      return Session.set('level', c.level);
    };

    AppRouter.prototype.achievements = function(id, tab) {
      this.softReset();
      Session.set('page', 'achievements');
      Session.set('limit', 'all');
      Session.set('single', id);
      if (!tab) {
        tab = 'info';
      }
      return Session.set('tab', tab);
    };

    AppRouter.prototype.accomplishments = function(id, tab) {
      this.softReset();
      Session.set('page', 'accomplishments');
      Session.set('limit', 'all');
      Session.set('single', id);
      if (!tab) {
        tab = 'info';
      }
      return Session.set('tab', tab);
    };

    AppRouter.prototype.user = function(user) {
      console.log(user);
      return this.profile();
    };

    AppRouter.prototype.profile = function(menu) {
      this.softReset();
      Session.set('page', 'profile');
      if (!menu) {
        menu = 'activity';
      }
      Session.set('menu', menu);
      return false;
    };

    AppRouter.prototype.softReset = function() {
      Session.set('expand', null);
      Session.set('story', null);
      Session.set('parent', null);
      return Session.set('level', 0);
    };

    AppRouter.prototype.hardReset = function() {
      this.softReset();
      $(document).scrollTop(0);
      Session.set('single', null);
      Session.set('tab', null);
      return Session.set('unexpand', null);
    };

    return AppRouter;

  })(Backbone.Router);

  window.Router = new AppRouter;

  Meteor.startup(function() {
    return Backbone.history.start({
      pushState: true
    });
  });

}).call(this);
