// Generated by CoffeeScript 1.3.3
(function() {

  Session.set('styleGuide', true);

  Session.set('editUsername', false);

  Meteor.subscribe('ushers', function() {
    var userId, userName;
    if (cookie.get('user')) {
      userId = cookie.get('user');
      return Session.set('user', userId);
    } else {
      userName = Math.floor(1000000 + (Math.random() * ((9999999 - 1000000) + 1)));
      userId = Ushers.insert({
        name: userName
      });
      Session.set('user', userId);
      return cookie.set('user', userId);
    }
  });

  Session.set('activitiesLoaded', false);

  Meteor.subscribe('activities', function() {
    return Session.set('activitiesLoaded', true);
  });

  Meteor.subscribe('drafts', Session.get('user'));

  Session.set('topic', 'dashboard');

  Meteor.autosubscribe(function() {
    var achievement, topic;
    topic = Session.get('single');
    if (topic) {
      Session.set('commentsLoaded', false);
      Meteor.subscribe('comments', topic, function() {
        return Session.set('commentsLoaded', true);
      });
    }
    achievement = Session.get('single');
    if (achievement) {
      Session.set('titlesLoaded', false);
      return Meteor.subscribe('titles', achievement, function() {
        return Session.set('titlesLoaded', true);
      });
    }
  });

  Session.set('achievements', false);

  Meteor.subscribe('achievements', function() {
    var id;
    Session.set('achievementsLoaded', true);
    id = window.createNewAchievement();
    return Session.set('newAchievement', id);
  });

  Session.set('votesLoaded', false);

  Meteor.subscribe('votes', function() {
    return Session.set('votesLoaded', true);
  });

  Session.set('favsLoaded', false);

  Meteor.subscribe('favourites', function() {
    return Session.set('favsLoaded', true);
  });

  Meteor.subscribe('users');

  Session.set('accomplishmentsLoaded', false);

  Meteor.subscribe('accomplishments', function() {
    return Session.set('accomplishmentsLoaded', true);
  });

}).call(this);
