// Generated by CoffeeScript 1.3.3
(function() {

  Session.set('styleGuide', true);

  Meteor.subscribe('users');

  Meteor.subscribe('comments');

  Meteor.autosubscribe(function() {
    var achievement;
    achievement = Session.get('single');
    if (achievement) {
      return Meteor.subscribe('titles', achievement, function() {});
    }
  });

  Meteor.subscribe('achievements', function() {
    var id;
    id = window.createNewAchievement();
    return Session.set('newAchievement', id);
  });

  Meteor.subscribe('votes', function() {});

  Meteor.subscribe('favourites', function() {});

  Meteor.subscribe('accomplishments', function() {});

}).call(this);
